### ISSUE TITLE
error when creating a  nonviral database

### ISSUE THREAD

**Issue by carloshenriquezc** [putonti/virMine#6]
Thanks for the implementation of this program.

I receive an error when creating the viral and non-viral databases. 
The viral database was created correctly, however i receive an error message when creating the non viral database. 

here we go:

Getting COG files
virmine_make2_dbs.py:15: DeprecationWarning: `use_list_a_option` will default to `False` in ftputil 4.x.x
  host=ftputil.FTPHost('ftp.ncbi.nih.gov','anonymous','password')
Preparing bacterial files for database. Removing phage/plasmid sequences.
Traceback (most recent call last):
  File "virmine_make2_dbs.py", line 36, in <module>
    for row in tab_rows:
  File "/home/usuario/miniconda3/lib/python3.7/csv.py", line 112, in __next__
    row = next(self.reader)
  File "/home/usuario/miniconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 6014: invalid start byte

Thanks in advance

**Comment by alemi055** [comment]
Hi! I got the same error. 
Did you find a way to fix it?
