### ISSUE TITLE
Virus database download error

### ISSUE THREAD

**Issue by xiaozhangzhang123** [putonti/virMine#9]
The downloaded virus database all.faa.tar.gz cannot be opened,the decompressed file all_viral_faa.fasta is empty.Is there any other way to download it,or if you can just send me the data set?

**Comment by katievigil** [comment]
Hi, I am having the same issue with trying to download the database.  What was the solution?
(/lustre/project/taw/share/conda-envs/build-dbs-env) [kvigil@cypress01-119 virmine]$ python virmine_make_dbs.py
Getting viral data from NCBI
Traceback (most recent call last):
  File "/lustre/project/taw/share/conda-envs/build-dbs-env/lib/python3.10/site-packages/ftputil/file.py", line 94, in _open
    self._conn = self._session.transfercmd(command, rest)
  File "/lustre/project/taw/share/conda-envs/build-dbs-env/lib/python3.10/ftplib.py", line 393, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/lustre/project/taw/share/conda-envs/build-dbs-env/lib/python3.10/ftplib.py", line 359, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/lustre/project/taw/share/conda-envs/build-dbs-env/lib/python3.10/ftplib.py", line 281, in sendcmd
    return self.getresp()
  File "/lustre/project/taw/share/conda-envs/build-dbs-env/lib/python3.10/ftplib.py", line 254, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 all.faa.tar.gz: No such file or directory
